name: Fail Check

on:
  pull_request:
    branches:
      - main

jobs:
  always-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Intentional success
        run: |
          echo "This step will pass intentionally."
          exit 0
